project:
  type: book
  output-dir: E:/CASA0023Remote sense/CASA0023-Learning-diary/docs

book:
  title: "Diary"
  author: "Yuqing Liu"
  date: "2024/3/13"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - week1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

