project:
  type: book
  output-dir: E:/CASA0023Remote sense/CASA0023-Learning-diary/docs

book:
  title: "<span style='color: black;'>Remote Sensing Learning Diary</span>" 
  #author: "Yuqing Liu"
  favicon: "img/ucl.png"
  navbar:
    logo: "img/casa_logo.jpg"
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "<span style='color:black;'>CASA0023 Learning Diary</span>" 
    style: docked
    reader-mode: true
  repo-url: https://github.com/lynneliu127/CASA0023-Learning-diary.git
  repo-actions: [issue]
  #date: "2024/3/13"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: img/nasa_earth_grid.jpg
    theme: cosmo
    code-link: true
    fontsize: 14pt
  pdf:
    documentclass: article
    fontsize: 14pt

editor: visual
